import React from "react";
import DocPage, { Section } from "../../../../components/DocPage";
import Callout from "../../../../components/Callout";
import DocImage from "../../../../components/DocImage";

const toc = [
  { id: "overview", label: "Overview" },
  { id: "purpose", label: "Purpose" },
  { id: "business-scenario", label: "Business Scenario" },
  { id: "when-to-use", label: "When To Use" },
  { id: "how-it-works", label: "How It Works" },
  { id: "configuration", label: "Configuration Options" },
  { id: "designer-behavior", label: "Designer Behaviour" },
  { id: "properties", label: "Supported Properties" },
  { id: "validation", label: "Validation Rules" },
  { id: "use-cases", label: "Common Use Cases" },
  { id: "mistakes", label: "Common Mistakes" },
  { id: "troubleshooting", label: "Troubleshooting" },
  { id: "related", label: "Related Elements" },
];

export default function HeaderElement() {
  return (
    <DocPage
      path="/reports/report-builder/elements/header"
      eyebrow="Report Builder · Elements"
      title="Header"
      description="The Header element renders the organisation logo, dispatch reference, vessel details, and port metadata at the top of every report page."
      toc={toc}
    >
      <Section id="overview" title="Overview">
        <p>
          The <strong>Header</strong> is the first visible block in every report layout. It anchors the document with corporate branding and key operational identifiers, ensuring recipients can immediately identify the report's origin and the contract it relates to.
        </p>
        <DocImage path="/reports/report-builder/elements/header" />
      </Section>

      <Section id="purpose" title="Purpose">
        <p>
          The Header element exists to provide a consistent, professional opening to every PDF report generated by the platform. It eliminates the need to manually repeat branding or contract metadata at the start of each document.
        </p>
      </Section>

      <Section id="business-scenario" title="Business Scenario">
        <p>
          A cargo surveyor completes an inspection at the Port of Singapore. When the report is generated, the Header automatically populates with the company logo, the contract BL number (<code>BL-2024-0892</code>), the vessel name (<em>MV Pacific Star</em>), the port of loading, and the report date. The client receives a branded document without the coordinator needing to manually fill in any header fields.
        </p>
      </Section>

      <Section id="when-to-use" title="When To Use">
        <ul className="list-disc pl-5 space-y-1.5 my-3 text-[13.5px]">
          <li>Every report template must include exactly <strong>one Header element</strong> — it is mandatory.</li>
          <li>Place the Header as the first element in the layout before any other content blocks.</li>
          <li>Use the Header to establish corporate identity and tie the report to a specific contract or dispatch.</li>
        </ul>
      </Section>

      <Section id="how-it-works" title="How It Works">
        <p>
          At report generation time, the platform reads the active contract's metadata and injects values into the Header's variable slots. The Header renders as a fixed-position block at the top of the first page and can optionally repeat on all subsequent pages.
        </p>
        <table>
          <thead>
            <tr><th>Variable Slot</th><th>Data Source</th><th>Example Value</th></tr>
          </thead>
          <tbody>
            <tr><td>Organisation Logo</td><td>Branding settings upload</td><td>[Company Logo Image]</td></tr>
            <tr><td>Company Name</td><td>Branding settings</td><td>CargoClave Surveying Ltd.</td></tr>
            <tr><td>BL / Contract Number</td><td>Active contract record</td><td>BL-2024-0892</td></tr>
            <tr><td>Vessel Name</td><td>Active contract record</td><td>MV Pacific Star</td></tr>
            <tr><td>Port of Loading</td><td>Active contract record</td><td>Port of Singapore</td></tr>
            <tr><td>Report Date</td><td>Auto-generated at render time</td><td>04 Aug 2026</td></tr>
          </tbody>
        </table>
      </Section>

      <Section id="configuration" title="Configuration Options">
        <table>
          <thead>
            <tr><th>Setting</th><th>Description</th><th>Default</th></tr>
          </thead>
          <tbody>
            <tr><td>Logo Position</td><td>Left, centre, or right alignment of the organisation logo within the header band.</td><td>Left</td></tr>
            <tr><td>Logo Size</td><td>Small (40px), Medium (60px), or Large (80px) height. Width scales proportionally.</td><td>Medium</td></tr>
            <tr><td>Show Company Name</td><td>Toggle the text company name display alongside or below the logo.</td><td>On</td></tr>
            <tr><td>Metadata Fields</td><td>Select which contract fields (BL No., Vessel, Port, Date) appear in the right column of the header band.</td><td>All enabled</td></tr>
            <tr><td>Repeat on Pages</td><td>Print the header on every page of the PDF, not just the first.</td><td>Off</td></tr>
            <tr><td>Background Colour</td><td>Hex colour fill for the header band background.</td><td>White (#FFFFFF)</td></tr>
            <tr><td>Border Bottom</td><td>Show a horizontal divider line beneath the header band.</td><td>On</td></tr>
          </tbody>
        </table>
      </Section>

      <Section id="designer-behavior" title="Designer Behaviour">
        <ul className="list-disc pl-5 space-y-1.5 my-3 text-[13.5px]">
          <li>The Header block is always <strong>pinned to the first position</strong> in the layout and cannot be reordered below other elements.</li>
          <li>Clicking the Header block opens its properties panel on the right side of the designer.</li>
          <li>Changes to the Header are previewed in real time in the right-hand PDF simulation panel.</li>
          <li>If no logo is uploaded in Branding settings, the logo slot displays a grey placeholder box in the preview.</li>
        </ul>
      </Section>

      <Section id="properties" title="Supported Properties">
        <table>
          <thead>
            <tr><th>Property</th><th>Type</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td>logoSrc</td><td>Image URL</td><td>The uploaded logo image from Branding settings.</td></tr>
            <tr><td>logoAlign</td><td>Enum (left / center / right)</td><td>Horizontal logo alignment.</td></tr>
            <tr><td>showCompanyName</td><td>Boolean</td><td>Whether to render the company name text.</td></tr>
            <tr><td>metadataFields</td><td>Array of field keys</td><td>Which contract metadata fields to display in the right column.</td></tr>
            <tr><td>repeatOnAllPages</td><td>Boolean</td><td>Whether the header repeats on subsequent PDF pages.</td></tr>
            <tr><td>backgroundColor</td><td>Hex colour</td><td>Background fill of the header band.</td></tr>
            <tr><td>borderBottom</td><td>Boolean</td><td>Show a bottom border divider line.</td></tr>
          </tbody>
        </table>
      </Section>

      <Section id="validation" title="Validation Rules">
        <Callout type="warning">
          Every report template <strong>must contain exactly one Header element</strong>. Attempting to publish a template without a Header will block publication with a validation error.
        </Callout>
        <Callout type="note">
          If the logo image URL is broken or the S3 asset is unavailable at render time, the Header renders without the logo image but continues generating the rest of the report normally.
        </Callout>
      </Section>

      <Section id="use-cases" title="Common Use Cases">
        <ul className="list-disc pl-5 space-y-1.5 my-3 text-[13.5px]">
          <li>Branded cargo inspection reports delivered to shipping lines and port authorities.</li>
          <li>Multi-page tally reports where the header repeats to identify every page.</li>
          <li>Client-specific report templates using different logos per client Branding profile.</li>
          <li>Internal audit reports using the company's internal branding without client metadata.</li>
        </ul>
      </Section>

      <Section id="mistakes" title="Common Mistakes">
        <Callout type="warning">
          Do not add a second Header element manually. The designer enforces one Header per template. Adding a Label/Value block with logo-like content at the top as a workaround will break the PDF layout alignment on all pages.
        </Callout>
        <Callout type="warning">
          Uploading a JPEG logo with a white background on a coloured header band produces a visible white box around the logo. Always use PNG with transparency.
        </Callout>
      </Section>

      <Section id="related" title="Related Elements">
        <ul className="list-disc pl-5 space-y-1.5 my-3 text-[13.5px]">
          <li><a href="/reports/report-builder/elements/label-value">Label / Value</a> — For displaying individual contract metadata fields in the body of the report.</li>
          <li><a href="/reports/report-builder/branding">Branding</a> — Configure the logo, colours, and company details used by the Header element.</li>
          <li><a href="/reports/report-builder/elements/signature">Signature</a> — The closing element that mirrors the Header's role of anchoring document identity.</li>
        </ul>
      </Section>
    </DocPage>
  );
}
